// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// new_a_dcc_loglik
NumericVector new_a_dcc_loglik(NumericVector param, arma::mat res, Nullable<int> K_c_in);
RcppExport SEXP _gmxdcc_new_a_dcc_loglik(SEXP paramSEXP, SEXP resSEXP, SEXP K_c_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type param(paramSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type res(resSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type K_c_in(K_c_inSEXP);
    rcpp_result_gen = Rcpp::wrap(new_a_dcc_loglik(param, res, K_c_in));
    return rcpp_result_gen;
END_RCPP
}
// new_a_dcc_mat_est
List new_a_dcc_mat_est(NumericVector est_param, arma::mat res, arma::cube Dt, Nullable<int> K_c_in, Nullable<NumericMatrix> S_in, Nullable<NumericMatrix> N_in);
RcppExport SEXP _gmxdcc_new_a_dcc_mat_est(SEXP est_paramSEXP, SEXP resSEXP, SEXP DtSEXP, SEXP K_c_inSEXP, SEXP S_inSEXP, SEXP N_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type est_param(est_paramSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type res(resSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Dt(DtSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type K_c_in(K_c_inSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type S_in(S_inSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type N_in(N_inSEXP);
    rcpp_result_gen = Rcpp::wrap(new_a_dcc_mat_est(est_param, res, Dt, K_c_in, S_in, N_in));
    return rcpp_result_gen;
END_RCPP
}
// new_dcc_loglik
NumericVector new_dcc_loglik(NumericVector param, arma::mat res, Nullable<int> K_c_in);
RcppExport SEXP _gmxdcc_new_dcc_loglik(SEXP paramSEXP, SEXP resSEXP, SEXP K_c_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type param(paramSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type res(resSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type K_c_in(K_c_inSEXP);
    rcpp_result_gen = Rcpp::wrap(new_dcc_loglik(param, res, K_c_in));
    return rcpp_result_gen;
END_RCPP
}
// new_dcc_mat_est
List new_dcc_mat_est(NumericVector est_param, arma::mat res, arma::cube Dt, Nullable<int> K_c_in, Nullable<NumericMatrix> S_in);
RcppExport SEXP _gmxdcc_new_dcc_mat_est(SEXP est_paramSEXP, SEXP resSEXP, SEXP DtSEXP, SEXP K_c_inSEXP, SEXP S_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type est_param(est_paramSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type res(resSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Dt(DtSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type K_c_in(K_c_inSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type S_in(S_inSEXP);
    rcpp_result_gen = Rcpp::wrap(new_dcc_mat_est(est_param, res, Dt, K_c_in, S_in));
    return rcpp_result_gen;
END_RCPP
}
// new_deco_loglik
NumericVector new_deco_loglik(NumericVector param, arma::mat res, Nullable<int> K_c_in);
RcppExport SEXP _gmxdcc_new_deco_loglik(SEXP paramSEXP, SEXP resSEXP, SEXP K_c_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type param(paramSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type res(resSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type K_c_in(K_c_inSEXP);
    rcpp_result_gen = Rcpp::wrap(new_deco_loglik(param, res, K_c_in));
    return rcpp_result_gen;
END_RCPP
}
// new_deco_mat_est
List new_deco_mat_est(NumericVector est_param, arma::mat res, arma::cube Dt, Nullable<int> K_c_in, Nullable<NumericMatrix> S_in);
RcppExport SEXP _gmxdcc_new_deco_mat_est(SEXP est_paramSEXP, SEXP resSEXP, SEXP DtSEXP, SEXP K_c_inSEXP, SEXP S_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type est_param(est_paramSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type res(resSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Dt(DtSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type K_c_in(K_c_inSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type S_in(S_inSEXP);
    rcpp_result_gen = Rcpp::wrap(new_deco_mat_est(est_param, res, Dt, K_c_in, S_in));
    return rcpp_result_gen;
END_RCPP
}
// fast_garch_ll_cpp
NumericVector fast_garch_ll_cpp(double alpha, double beta, double mu, NumericVector epsilon, NumericVector tau_d, NumericVector daily_ret);
RcppExport SEXP _gmxdcc_fast_garch_ll_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP muSEXP, SEXP epsilonSEXP, SEXP tau_dSEXP, SEXP daily_retSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau_d(tau_dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type daily_ret(daily_retSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_garch_ll_cpp(alpha, beta, mu, epsilon, tau_d, daily_ret));
    return rcpp_result_gen;
END_RCPP
}
// fast_t_garch_ll
NumericVector fast_t_garch_ll(double alpha, double beta, double v, NumericVector epsilon, NumericVector tau_d, NumericVector daily_ret);
RcppExport SEXP _gmxdcc_fast_t_garch_ll(SEXP alphaSEXP, SEXP betaSEXP, SEXP vSEXP, SEXP epsilonSEXP, SEXP tau_dSEXP, SEXP daily_retSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau_d(tau_dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type daily_ret(daily_retSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_t_garch_ll(alpha, beta, v, epsilon, tau_d, daily_ret));
    return rcpp_result_gen;
END_RCPP
}
// midas_ll_rcpp
arma::vec midas_ll_rcpp(int TT, int Num_assets, int K_c, double a, double b, arma::cube R_t_bar, arma::mat res);
RcppExport SEXP _gmxdcc_midas_ll_rcpp(SEXP TTSEXP, SEXP Num_assetsSEXP, SEXP K_cSEXP, SEXP aSEXP, SEXP bSEXP, SEXP R_t_barSEXP, SEXP resSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< int >::type Num_assets(Num_assetsSEXP);
    Rcpp::traits::input_parameter< int >::type K_c(K_cSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type R_t_bar(R_t_barSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type res(resSEXP);
    rcpp_result_gen = Rcpp::wrap(midas_ll_rcpp(TT, Num_assets, K_c, a, b, R_t_bar, res));
    return rcpp_result_gen;
END_RCPP
}
// midas_rc_rcpp
arma::cube midas_rc_rcpp(int N_c, int Num_assets, int TT, arma::mat res);
RcppExport SEXP _gmxdcc_midas_rc_rcpp(SEXP N_cSEXP, SEXP Num_assetsSEXP, SEXP TTSEXP, SEXP resSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N_c(N_cSEXP);
    Rcpp::traits::input_parameter< int >::type Num_assets(Num_assetsSEXP);
    Rcpp::traits::input_parameter< int >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type res(resSEXP);
    rcpp_result_gen = Rcpp::wrap(midas_rc_rcpp(N_c, Num_assets, TT, res));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gmxdcc_new_a_dcc_loglik", (DL_FUNC) &_gmxdcc_new_a_dcc_loglik, 3},
    {"_gmxdcc_new_a_dcc_mat_est", (DL_FUNC) &_gmxdcc_new_a_dcc_mat_est, 6},
    {"_gmxdcc_new_dcc_loglik", (DL_FUNC) &_gmxdcc_new_dcc_loglik, 3},
    {"_gmxdcc_new_dcc_mat_est", (DL_FUNC) &_gmxdcc_new_dcc_mat_est, 5},
    {"_gmxdcc_new_deco_loglik", (DL_FUNC) &_gmxdcc_new_deco_loglik, 3},
    {"_gmxdcc_new_deco_mat_est", (DL_FUNC) &_gmxdcc_new_deco_mat_est, 5},
    {"_gmxdcc_fast_garch_ll_cpp", (DL_FUNC) &_gmxdcc_fast_garch_ll_cpp, 6},
    {"_gmxdcc_fast_t_garch_ll", (DL_FUNC) &_gmxdcc_fast_t_garch_ll, 6},
    {"_gmxdcc_midas_ll_rcpp", (DL_FUNC) &_gmxdcc_midas_ll_rcpp, 7},
    {"_gmxdcc_midas_rc_rcpp", (DL_FUNC) &_gmxdcc_midas_rc_rcpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_gmxdcc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
