# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

new_a_dcc_loglik <- function(param, res, K_c_in = NULL) {
    .Call(`_gmxdcc_new_a_dcc_loglik`, param, res, K_c_in)
}

new_a_dcc_mat_est <- function(est_param, res, Dt, K_c_in = NULL, S_in = NULL, N_in = NULL) {
    .Call(`_gmxdcc_new_a_dcc_mat_est`, est_param, res, Dt, K_c_in, S_in, N_in)
}

new_dcc_loglik <- function(param, res, K_c_in = NULL) {
    .Call(`_gmxdcc_new_dcc_loglik`, param, res, K_c_in)
}

new_dcc_mat_est <- function(est_param, res, Dt, K_c_in = NULL, S_in = NULL) {
    .Call(`_gmxdcc_new_dcc_mat_est`, est_param, res, Dt, K_c_in, S_in)
}

new_deco_loglik <- function(param, res, K_c_in = NULL) {
    .Call(`_gmxdcc_new_deco_loglik`, param, res, K_c_in)
}

new_deco_mat_est <- function(est_param, res, Dt, K_c_in = NULL, S_in = NULL) {
    .Call(`_gmxdcc_new_deco_mat_est`, est_param, res, Dt, K_c_in, S_in)
}

fast_garch_ll_cpp <- function(alpha, beta, mu, epsilon, tau_d, daily_ret) {
    .Call(`_gmxdcc_fast_garch_ll_cpp`, alpha, beta, mu, epsilon, tau_d, daily_ret)
}

fast_t_garch_ll <- function(alpha, beta, v, epsilon, tau_d, daily_ret) {
    .Call(`_gmxdcc_fast_t_garch_ll`, alpha, beta, v, epsilon, tau_d, daily_ret)
}

midas_ll_rcpp <- function(TT, Num_assets, K_c, a, b, R_t_bar, res) {
    .Call(`_gmxdcc_midas_ll_rcpp`, TT, Num_assets, K_c, a, b, R_t_bar, res)
}

midas_rc_rcpp <- function(N_c, Num_assets, TT, res) {
    .Call(`_gmxdcc_midas_rc_rcpp`, N_c, Num_assets, TT, res)
}

